const allergies = [
    "Beef",
    "Dairy",
    "Chicken",
    "Lamb",
    "Fish",
    "Corn",
    "Wheat",
    "Soy",
    "Pork",
    "Rabbit",
    "Egg",
    "Duck",
    "Turkey",
    "Rice",
    "Potato",
    "Peas",
    "Sweet Potatoes",
    "Carrots",
    "Barley",
    "Oats",
    "Chicken Eggs",
    "Venison",
    "Kangaroo",
    "Buffalo",
    "Millet",
    "Quinoa",
    "Lentils",
    "Garbanzo Beans",
    "Flaxseed",
    "Yeast",
    "Tomato",
    "Apples",
    "Bananas",
    "Strawberries",
    "Blueberries",
    "Peanuts",
    "Almonds",
    "Cheese",
    "Yogurt",
    "Gluten",
    "Artificial Colors",
    "Artificial Flavors",
    "Artificial Preservatives",
    "Fillers",
    "Additives",
    "Pork Fat",
    "Beef Fat",
    "Chicken Fat",
    "Lamb Fat",
    "Fish Oil",
    "Sunflower Oil",
    "Olive Oil",
    "Canola Oil",
    "Palm Oil",
    "Coconut Oil",
    "Peanut Oil",
    "Corn Oil",
    "Safflower Oil",
    "Soybean Oil",
    "Cottonseed Oil",
    "Grapeseed Oil",
    "Sesame Oil",
    "Avocado",
    "Broccoli",
    "Cauliflower",
    "Spinach",
    "Kale",
    "Brussels Sprouts",
    "Cabbage",
    "Celery",
    "Cucumber",
    "Green Beans",
    "Peppers",
    "Zucchini",
    "Squash",
    "Pumpkin",
    "Mushrooms",
    "Onions",
    "Garlic",
    "Chives",
    "Leeks",
    "Shallots",
    "Scallions",
    "Asparagus",
    "Eggplant",
    "Radishes",
    "Turnips",
    "Beets",
    "Parsnips",
    "Rutabaga",
    "Horseradish",
    "Ginger",
    "Turmeric",
    "Cinnamon",
    "Nutmeg",
    "Cloves",
    "Cardamom",
    "Anise",
    "Fennel",
    "Coriander",
    "Cumin",
    "Sage",
    "Rosemary",
    "Thyme",
    "Basil",
    "Oregano",
    "Parsley",
    "Dill",
    "Mint",
    "Chervil",
    "Tarragon",
    "Marjoram",
    "Lavender",
    "Lemongrass"
]

export default allergies;