const breeds = [
  "Labrador Retriever",
  "German Shepherd",
  "Golden Retriever",
  "French Bulldog",
  "Bulldog",
  "Poodle",
  "Beagle",
  "Rottweiler",
  "German Shorthaired Pointer",
  "Yorkshire Terrier",
  "Boxer",
  "Siberian Husky",
  "Dachshund",
  "Great Dane",
  "Doberman Pinscher",
  "Australian Shepherd",
  "Cavalier King Charles Spaniel",
  "Miniature Schnauzer",
  "Shih Tzu",
  "Boston Terrier",
  "Bernese Mountain Dog",
  "Pomeranian",
  "Havanese",
  "Shetland Sheepdog",
  "Brittany",
  "English Springer Spaniel",
  "Cocker Spaniel",
  "Pembroke Welsh Corgi",
  "Vizsla",
  "Chihuahua",
  "Basset Hound",
  "Border Collie",
  "Weimaraner",
  "Newfoundland",
  "Collie",
  "Bichon Frise",
  "Rhodesian Ridgeback",
  "West Highland White Terrier",
  "Belgian Malinois",
  "Akita",
  "St. Bernard",
  "Bloodhound",
  "Bullmastiff",
  "English Bulldog",
  "American Staffordshire Terrier",
  "Mastiff",
  "Old English Sheepdog",
  "Cane Corso",
  "Alaskan Malamute",
  "Samoyed",
  "Scottish Terrier",
  "Soft Coated Wheaten Terrier",
  "Irish Setter",
  "Dalmatian",
  "Whippet",
  "Chinese Shar-Pei",
  "Chow Chow",
  "Australian Cattle Dog",
  "Pointer",
  "Lhasa Apso",
  "Bull Terrier",
  "Shiba Inu",
  "Airedale Terrier",
  "Alaskan Klee Kai",
  "American Bulldog",
  "American Eskimo Dog",
  "Basenji",
  "Bavarian Mountain Scent Hound",
  "Bearded Collie",
  "Belgian Sheepdog",
  "Belgian Tervuren",
  "Black Russian Terrier",
  "Boerboel",
  "Bolognese",
  "Border Terrier",
  "Borzoi",
  "Brussels Griffon",
  "Cairn Terrier",
  "Canaan Dog",
  "Cardigan Welsh Corgi",
  "Catahoula Leopard Dog",
  "Caucasian Shepherd Dog",
  "Cavalier King Charles Spaniel",
  "Cesky Terrier",
  "Clumber Spaniel",
  "Coton de Tulear",
  "Curly-Coated Retriever",
  "Dandie Dinmont Terrier",
  "Doberman Pinscher",
  "Dogo Argentino",
  "Dutch Shepherd",
  "English Foxhound",
  "English Setter",
  "English Toy Spaniel",
  "Entlebucher Mountain Dog",
  "Field Spaniel",
  "Finnish Lapphund",
  "Finnish Spitz",
  "Flat-Coated Retriever",
  "French Bulldog",
  "German Pinscher",
  "Glen of Imaal Terrier",
  "Goldador",
  "Golden Retriever",
  "Gordon Setter",
];

export default breeds;
